"""Independent regressions for meaning-preserving Humanize behavior.

The corpus reference edits are illustrative, not an automated quality oracle.
Author: Luke Steuber
"""

import dataclasses
import importlib.util
import json
from pathlib import Path
import sys
import tempfile
import unittest


ROOT = Path(__file__).resolve().parents[1]


def load_module(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


SCANNER = load_module("preservation_scanner", ROOT / "skills/humanize/scripts/doc_humanizer.py")
EVALUATOR = load_module("editorial_evaluator", ROOT / "tests/evaluate_editorial.py")
CORPUS = json.loads((ROOT / "tests/fixtures/editorial.json").read_text(encoding="utf-8"))
FILLER = "It is important to note that backups expire after 30 days."


class MeaningPreservationTests(unittest.TestCase):
    def setUp(self):
        self.humanizer = SCANNER.DocumentHumanizer()

    def test_previously_destructive_transforms_preserve_exact_text(self):
        cases = [
            "Generated by Alice Smith.",
            "Migration is not fully implemented.",
            "Made with Claude ✅ fully implemented",
            "The change appears to improve results, but might fail on older devices.",
            "The robust estimator gives an optimal solution.",
            "First — one\nsecond — two\nthird — three",
            "<a href=\"/robust?mode=optimal\">robust</a>",
            "~~~python\nrobust = \"optimal\"\n~~~\n",
            "---\nauthor: Alice Smith\nstatus: fully implemented\n---\n",
            "We are ready. Our work is done.",
            "The result is 95%, not 100%. Updated 2026-08-12.",
            "\ufeff# Résumé\r\n\r\nPerhaps it works.  \r\n",
            "\tkeep\tthese\tcolumns\r\n\r\n",
            "No final newline",
            "",
        ]
        for content in cases:
            with self.subTest(content=content):
                self.assertEqual(self.humanizer.apply_transforms(content), content)
                self.assertEqual(self.humanizer.apply_transforms(
                    self.humanizer.apply_transforms(content)), content)

    def test_all_editorial_examples_remain_unchanged_by_mechanical_fixer(self):
        for case in CORPUS["cases"]:
            for field in ("original", "reference"):
                with self.subTest(case=case["id"], field=field):
                    text = case[field]
                    self.assertEqual(self.humanizer.apply_transforms(text), text)

    def test_empty_and_plain_good_prose_have_no_findings(self):
        for content in ("", "Save the file before closing the window."):
            self.assertEqual(self.humanizer.scan_text(content), [])

    def test_findings_preserve_original_coordinates_and_match(self):
        content = "Résumé 🪴\r\n\r\n" + FILLER
        findings = [finding for finding in self.humanizer.scan_text(content)
                    if finding.rule_id == "H001"]
        self.assertEqual(len(findings), 1)
        finding = findings[0]
        self.assertTrue(dataclasses.is_dataclass(finding))
        self.assertEqual(finding.line, 3)
        self.assertEqual(finding.column, 1)
        self.assertEqual(finding.start, content.index("It is important"))
        self.assertGreater(finding.end, finding.start)
        self.assertEqual(content[finding.start:finding.end], finding.text)
        self.assertFalse(finding.autofix)
        self.assertTrue(finding.message)
        self.assertTrue(finding.suggestion)
        self.assertTrue(finding.severity)

    def test_mixed_inline_code_and_prose_still_reports_prose(self):
        content = f"Run `{FILLER}` first. {FILLER}"
        findings = [finding for finding in self.humanizer.scan_text(content)
                    if finding.rule_id == "H001"]
        self.assertEqual(len(findings), 1)
        self.assertEqual(findings[0].start, content.rindex("It is important"))
        self.assertEqual(findings[0].column, findings[0].start + 1)

    def test_protected_markdown_does_not_emit_prose_findings(self):
        cases = {
            "backtick fence": f"```text\n{FILLER}\n```\n",
            "tilde fence": f"~~~text\n{FILLER}\n~~~\n",
            "long fence": f"````text\n```\n{FILLER}\n````\n",
            "unclosed fence": f"```text\n{FILLER}",
            "short closer": f"~~~~text\n~~~\n{FILLER}",
            "indented code": f"    {FILLER}\n",
            "tab code": f"\t{FILLER}\n",
            "inline code": f"`{FILLER}`",
            "long inline delimiter": f"``literal ` {FILLER}``",
            "link": f"[{FILLER}](https://example.org/robust)",
            "image": f"![{FILLER}](image.png)",
            "reference definition": f"[source]: https://example.org \"{FILLER}\"\n",
            "blockquote": f"> {FILLER}\n",
            "nested blockquote": f"> > {FILLER}\n",
            "double quotation": f'He wrote "{FILLER}" yesterday.',
            "curly quotation": f"He wrote “{FILLER}” yesterday.",
            "escaped double quotation": f'She said "literal \\"quoted\\" {FILLER}".',
            "escaped single quotation": f"She said 'it\\'s fine. {FILLER}'.",
            "multiline quotation": f'She said "First line\n{FILLER}".',
            "front matter": f"---\ntitle: {FILLER}\n---\n",
            "TOML front matter": f"+++\ntitle = \"{FILLER}\"\n+++\n",
            "HTML attribute": f'<a title="{FILLER}" href="/robust">Link</a>',
            "HTML comment": f"<!--\n{FILLER}\n-->",
            "HTML script": f"<script>\n{FILLER}\n</script>",
            "HTML style": f"<style>\n{FILLER}\n</style>",
            "nested inline HTML": f"Before <span><span>inner</span>{FILLER}</span> after.",
        }
        for name, content in cases.items():
            with self.subTest(name=name):
                self.assertEqual(self.humanizer.scan_text(content, strict=True), [])

    def test_protection_ends_at_matching_fence(self):
        content = f"~~~\n{FILLER}\n~~~\n{FILLER}"
        findings = [finding for finding in self.humanizer.scan_text(content)
                    if finding.rule_id == "H001"]
        self.assertEqual(len(findings), 1)
        self.assertEqual(findings[0].line, 4)

    def test_results_are_deterministic_and_have_no_autofixes(self):
        content = FILLER + "\nThe result? A seamless and robust solution."
        first = self.humanizer.scan_text(content, strict=True)
        self.assertEqual(first, self.humanizer.scan_text(content, strict=True))
        self.assertTrue(first)
        self.assertTrue(all(not finding.autofix for finding in first))
        self.assertEqual([finding.start for finding in first],
                         sorted(finding.start for finding in first))

    def test_file_scan_rejects_instruction_and_unsupported_files(self):
        with tempfile.TemporaryDirectory() as directory:
            for name in ("AGENTS.md", "page.html", "source.py"):
                path = Path(directory) / name
                path.write_text(FILLER, encoding="utf-8")
                with self.subTest(name=name), self.assertRaises(ValueError):
                    self.humanizer.scan_file(str(path))


class EditorialCorpusTests(unittest.TestCase):
    def test_corpus_has_consistent_literals_and_separate_holdout_cases(self):
        self.assertEqual(EVALUATOR.validate_corpus(CORPUS), [])
        self.assertEqual(len(CORPUS["cases"]), 30)
        for split in ("development", "holdout"):
            cases = [case for case in CORPUS["cases"] if case["split"] == split]
            self.assertEqual(len(cases), 15)
            self.assertEqual({case["action"] for case in cases}, {"edit", "leave"})
            self.assertGreaterEqual(len({case["genre"] for case in cases}), 5)

    def test_reference_edits_pass_only_the_declared_literal_checks(self):
        candidates = {case["id"]: case["reference"] for case in CORPUS["cases"]}
        result = EVALUATOR.evaluate(CORPUS, candidates)
        self.assertEqual(result["literal_errors"], [])
        self.assertTrue(result["human_review_required"])

    def test_lost_negation_and_incomplete_candidate_sets_fail_evaluation(self):
        candidates = {case["id"]: case["reference"] for case in CORPUS["cases"]}
        candidates["release-limits"] = "The migration is fully implemented."
        del candidates["personal-weather"]
        result = EVALUATOR.evaluate(CORPUS, candidates)
        self.assertTrue(any("release-limits" in error for error in result["literal_errors"]))
        self.assertTrue(any("personal-weather" in error for error in result["literal_errors"]))

    def test_candidate_can_differ_from_reference_and_still_require_human_review(self):
        candidates = {case["id"]: case["original"] for case in CORPUS["cases"]}
        result = EVALUATOR.evaluate(CORPUS, candidates)
        self.assertEqual(result["literal_errors"], [])
        self.assertTrue(result["human_review_required"])


if __name__ == "__main__":
    unittest.main()
